Create own git hook document
DatabayAG/ILIAS pull request #2
Opened 2019-06-13 15:28 UTC by legionth

Documentation about the code style git hooks.

I don't know if this the right branch to merge, just give me feedback on this :+1:

2019-06-14 09:13 UTC, legionth commented
I could also create a PR after `ci_restructuring` into `ILIAS/trunk` :thinking:

2019-06-17 08:42 UTC, ILIASci approved these changes
Looks good to me, but like we discussed, we should think about separating the code examples into files and put them into [here](https://github.com/ILIAS-eLearning/DeveloperTools/tree/master/git_hooks) maybe.

2019-06-21 06:21 UTC, legionth commented
Created a branch on my own fork: https://github.com/legionth/DeveloperTools/tree/code-style-hooks/git_hooks/hooks

2019-07-03 11:30 UTC, mjansenDatabay commented on docs/documentation/git-hooks.md
> +This document will list some useful git hooks to create a better development
Wir sollten Begriffe wie "GIT" einheitlich nutzen, d.h. "GIT", "git", oder "Git", nur überall gleich.

2019-07-03 16:11 UTC, mjansenDatabay commented
Who is @ILIASci :-)?

2019-07-03 16:12 UTC, mjansenDatabay commented on docs/documentation/git-hooks.md
> +This document will list some useful Git hooks to create a better development
`This document lists some useful Git hooks to create a better development`

2019-07-03 16:13 UTC, mjansenDatabay commented on docs/documentation/git-hooks.md
> +only, and may not be used in actual environments__
`actual` = `in production`

2019-07-03 16:15 UTC, mjansenDatabay requested changes
Only some minor remarks.

I also think the separation of the examples into separate files would be great.

2019-07-04 06:23 UTC, legionth commented
> I also think the separation of the examples into separate files would be great.
Then we wouldn't need to add these hooks to the https://github.com/ILIAS-eLearning/DeveloperTools.
IMO either we put the git hook files into the main repository or the developer tools not both.

Honestly I don't know if this README belongs in the main repository either.

2019-07-08 07:48 UTC, gvollbach commented
> Honestly I don't know if this README belongs in the main repository either.
To be honest I would put this README into the developer tools repo also and maybe put only a link, to the developer tools, at most. 

Also I would remove the source code from the README and link to the files in the delveloper tools directory.

2019-07-08 07:50 UTC, gvollbach commented
> Who is @ILIASci :-)?

It is a really early stage of a seriously dumb AI.  ;)

2019-07-10 11:26 UTC, mjansenDatabay approved these changes

2019-07-10 14:30 UTC, legionth commented
Review plx.

2019-07-12 06:22 UTC, gvollbach approved these changes
:+1:

2019-07-12 06:24 UTC, merged

2019-07-12 06:24 UTC, gvollbach commented
Thanks!